import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,doc,getDoc,getDocFromServer}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import'./scheduler-fixes.js';
const $=id=>document.getElementById(id);const cfg=await(await fetch('/__/firebase/init.json')).json();const fb=getApps()[0]||initializeApp(cfg);const db=getFirestore(fb);const root=doc(db,'gestionale','dati');
const countServices=[['guardia','GUARDIA NOTT.'],['giorno','GIORNO'],['disp1','1ª DISP.'],['disp2','2ª DISP.'],['gessi','GESSI MAT'],['gessirep','GESSI+REP POM'],['reparto','REPARTO'],['amb','AMBULATORIO'],['esami','AMB ESAMI'],['op1','OP1 MAT'],['op2','OP2 MAT'],['oppom','OP POM']];
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=(h+l-7*m+114)%31+1;return new Date(y,mo-1,da,12)}
function holiday(dt){let md=`${dt.getMonth()+1}-${dt.getDate()}`,fixed=new Set(['1-1','1-6','4-25','5-1','6-2','8-15','8-16','11-1','12-8','12-25','12-26']);if(fixed.has(md))return true;let p=easter(dt.getFullYear());p.setDate(p.getDate()+1);return p.toDateString()===dt.toDateString()}
function hoursFor(s,ds){let dt=new Date(ds+'T12:00:00');if(s==='guardia')return 12;if(['disp1','disp2'].includes(s))return[0,6].includes(dt.getDay())?6:0;return 6}
function monthlyTarget(d,m){const[y,mo]=m.split('-').map(Number),days=new Date(y,mo,0).getDate();let wd=d.name==='ARMATO'||d.name==='CIPRIAN'?[1,2,3,4,5]:d.name==='RIVA'?[1,2,3]:d.name==='FREGUIA'?[3,4,5]:null;if(wd){let n=0;for(let i=1;i<=days;i++){let x=new Date(y,mo-1,i,12);if(wd.includes(x.getDay())&&!holiday(x))n++}return n}if(d.name==='PINI')return Math.round(days/7*3);if(d.name==='LONDEI')return'Specifico';let n=0;for(let i=1;i<=days;i++){let x=new Date(y,mo-1,i,12);if(x.getDay()!==0&&!holiday(x))n++}return n}
async function freshCloud(){let snap;try{snap=await getDocFromServer(root)}catch{snap=await getDoc(root)}return snap.exists()?snap.data():{}}
function mergeVisibleGrid(schedule){document.querySelectorAll('#schedule select[data-k]').forEach(sel=>{const q=sel.dataset.k;if(!q)return;if(sel.value)schedule[q]=sel.value;else delete schedule[q]});return schedule}
async function recalcCounts(annual=false){const m=$('month')?.value;if(!m)return;const title=$('countTitle'),info=$('countInfo'),table=$('countTable'),modal=$('countModal');modal?.classList.remove('hidden');if(title)title.textContent=annual?'Conteggio totale annuale '+m.slice(0,4):'Conteggio turni del mese '+m;if(info)info.textContent='Ricalcolo in corso…';if(table)table.innerHTML='';try{const x=await freshCloud(),doctors=x.doctors||[],schedule=mergeVisibleGrid({...x.schedule||{}}),prefix=annual?m.slice(0,4)+'-':m,st={};doctors.forEach(d=>st[d.name]={eq:0,s:{},sat:0,sun:0});for(const[q,n]of Object.entries(schedule)){const[ds,s]=q.split('|');if(!ds.startsWith(prefix)||n==='NESSUNO'||!st[n])continue;st[n].eq+=hoursFor(s,ds)/6;if(s!=='ferie')st[n].s[s]=(st[n].s[s]||0)+1;if(!annual&&s!=='ferie'){const w=new Date(ds+'T12:00:00').getDay();if(w===6)st[n].sat++;if(w===0)st[n].sun++}}let html;if(annual){html='<tr><th>Medico</th><th>Turni 6h eq.</th>'+countServices.map(s=>`<th>${s[1]}</th>`).join('')+'</tr>';for(const d of doctors){const z=st[d.name]||{eq:0,s:{}};html+=`<tr><td><b>${d.name}</b></td><td>${z.eq}</td>${countServices.map(s=>`<td>${z.s[s[0]]||0}</td>`).join('')}</tr>`}}else{html='<tr><th>Medico</th><th>Notti</th><th>Target</th><th>Turni totali</th><th>OP MAT</th><th>OP POM</th><th>Sabato</th><th>Domenica</th></tr>';for(const d of doctors){const z=st[d.name]||{eq:0,s:{},sat:0,sun:0};const opMat=(z.s.op1||0)+(z.s.op2||0);html+=`<tr><td><b>${d.name}</b></td><td>${z.s.guardia||0}</td><td>${monthlyTarget(d,m)}</td><td>${z.eq}</td><td>${opMat}</td><td>${z.s.oppom||0}</td><td>${z.sat||0}</td><td>${z.sun||0}</td></tr>`}}table.innerHTML=html;const now=new Date().toLocaleTimeString('it-IT');info.textContent=(annual?'Totale gennaio–dicembre. ':'Conteggio mensile. ')+`Ricalcolato alle ${now}. Ferie = 6 h; disponibilità lun–ven = 0 h di servizio; disponibilità sab/dom = 6 h.`}catch(err){if(info)info.textContent='Errore durante il ricalcolo: '+err.message}}
$('countBtn')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();recalcCounts(false)},true);$('annualCountBtn')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();recalcCounts(true)},true);