import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,doc,getDoc,setDoc,updateDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const $=id=>document.getElementById(id),cfg=await(await fetch('/__/firebase/init.json')).json(),fb=getApps()[0]||initializeApp(cfg),db=getFirestore(fb),root=doc(db,'gestionale','dati');
const k=(ds,s,i)=>`${ds}|${s}|${i}`,MONTH_KEY='gestionale:selectedMonth';
document.head.insertAdjacentHTML('beforeend','<style>.extraShift{background:#fecaca!important;border:2px solid #dc2626!important;color:#991b1b!important;font-weight:700!important}</style>');
async function cloud(){let s=await getDoc(root);return s.exists()?s.data():{}}
async function saveSchedule(schedule,extraKeys){let patch={schedule,updatedAt:new Date().toISOString()};if(extraKeys!==undefined)patch.extraKeys=extraKeys;try{await updateDoc(root,patch)}catch(e){await setDoc(root,patch,{merge:true})}}
function rememberMonth(){let m=$('month')?.value;if(m)localStorage.setItem(MONTH_KEY,m)}
function restoreMonth(){let el=$('month'),m=localStorage.getItem(MONTH_KEY);if(el&&m&&/^\d{4}-\d{2}$/.test(m)&&el.value!==m){el.value=m;el.dispatchEvent(new Event('change',{bubbles:true}))}}
$('month')?.addEventListener('change',rememberMonth);$('prev')?.addEventListener('click',()=>setTimeout(rememberMonth));$('next')?.addEventListener('click',()=>setTimeout(rememberMonth));setTimeout(restoreMonth,0);setTimeout(restoreMonth,500);
const monthNames=['GENNAIO','FEBBRAIO','MARZO','APRILE','MAGGIO','GIUGNO','LUGLIO','AGOSTO','SETTEMBRE','OTTOBRE','NOVEMBRE','DICEMBRE'];
function printMonth(){let m=$('month')?.value;if(!m)return;rememberMonth();let[y,mo]=m.split('-').map(Number);$('printTitle').textContent=`TURNI ORTOPEDIA ${monthNames[mo-1]} ${y}`;document.querySelectorAll('#schedule .printValue').forEach(x=>x.remove());document.querySelectorAll('#schedule .cell').forEach(cell=>{let vals=[...cell.querySelectorAll('select')].map(s=>s.value).filter(v=>v&&v!=='NESSUNO');let sp=document.createElement('span');sp.className='printValue';sp.textContent=vals.length?vals.join(' - '):'-';cell.appendChild(sp)});window.print()}
$('printBtn')?.addEventListener('click',printMonth);
async function removeLeave(){let n=$('leaveDoctor')?.value,a=$('leaveStart')?.value,b=$('leaveEnd')?.value;if(!n||!a||!b||a>b)return alert('Controlla medico e date.');rememberMonth();let x=await cloud(),schedule={...(x.schedule||{})},extras=new Set(x.extraKeys||[]);for(let d=new Date(a+'T12:00:00'),e=new Date(b+'T12:00:00');d<=e;d.setDate(d.getDate()+1)){let ds=d.toISOString().slice(0,10);for(let i=0;i<4;i++){let q=k(ds,'ferie',i);if(schedule[q]===n){delete schedule[q];extras.delete(q)}}}await saveSchedule(schedule,[...extras]);$('leaveModal')?.classList.add('hidden');location.reload()}
$('removeLeave')?.addEventListener('click',removeLeave);
function enhanceLeaveCells(){document.querySelectorAll('#schedule .leaveCell').forEach(cell=>{let originals=[...cell.querySelectorAll('select')];if(!originals.length)return;let base=originals[0],baseKey=base.dataset.k;if(!baseKey)return;let ds=baseKey.split('|')[0];for(let i=originals.length;i<4;i++){let sel=base.cloneNode(true);sel.dataset.k=k(ds,'ferie',i);sel.value='';sel.disabled=false;sel.classList.remove('extraShift');cell.appendChild(sel)}for(const sel of cell.querySelectorAll('select')){if(sel.dataset.manualLeaveBound)return;sel.dataset.manualLeaveBound='1';sel.addEventListener('change',async e=>{rememberMonth();let x=await cloud(),schedule={...(x.schedule||{})},q=e.target.dataset.k;if(e.target.value)schedule[q]=e.target.value;else delete schedule[q];await saveSchedule(schedule)})}})}
const obs=new MutationObserver(enhanceLeaveCells);let table=$('schedule');if(table){obs.observe(table,{childList:true,subtree:true});enhanceLeaveCells()}