import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,doc,getDoc,setDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const $=id=>document.getElementById(id),cfg=await(await fetch('/__/firebase/init.json')).json(),fb=getApps()[0]||initializeApp(cfg),db=getFirestore(fb),root=doc(db,'gestionale','dati');
const monthNames=['GENNAIO','FEBBRAIO','MARZO','APRILE','MAGGIO','GIUGNO','LUGLIO','AGOSTO','SETTEMBRE','OTTOBRE','NOVEMBRE','DICEMBRE'];
async function cloud(){let s=await getDoc(root);return s.exists()?s.data():{}}
async function saveSchedule(schedule,generatedKeys){let patch={schedule,updatedAt:new Date().toISOString()};if(generatedKeys)patch.generatedKeys=generatedKeys;await setDoc(root,patch,{merge:true})}
function printMonth(){let m=$('month')?.value;if(!m)return;let[y,mo]=m.split('-').map(Number);$('printTitle').textContent=`TURNI ORTOPEDIA ${monthNames[mo-1]} ${y}`;document.querySelectorAll('#schedule .printValue').forEach(x=>x.remove());document.querySelectorAll('#schedule .cell').forEach(cell=>{let vals=[...cell.querySelectorAll('select')].map(s=>s.value).filter(v=>v&&v!=='NESSUNO');let sp=document.createElement('span');sp.className='printValue';sp.textContent=vals.length?vals.join(' - '):'-';cell.appendChild(sp)});window.print()}
$('printBtn')?.addEventListener('click',printMonth);
async function removeLeave(){let n=$('leaveDoctor')?.value,a=$('leaveStart')?.value,b=$('leaveEnd')?.value;if(!n||!a||!b||a>b)return alert('Controlla medico e date.');let x=await cloud(),schedule=x.schedule||{};for(let d=new Date(a+'T12:00:00'),e=new Date(b+'T12:00:00');d<=e;d.setDate(d.getDate()+1)){let ds=d.toISOString().slice(0,10);for(let i=0;i<4;i++){let k=`${ds}|ferie|${i}`;if(schedule[k]===n)delete schedule[k]}}await saveSchedule(schedule);$('leaveModal')?.classList.add('hidden');location.reload()}
$('removeLeave')?.addEventListener('click',removeLeave);
function enhanceLeaveCells(){document.querySelectorAll('#schedule .leaveCell').forEach(cell=>{if(cell.querySelectorAll('select').length>=4)return;let originals=[...cell.querySelectorAll('select')];if(!originals.length)return;let base=originals[0],baseKey=base.dataset.k;if(!baseKey)return;let ds=baseKey.split('|')[0];for(let i=originals.length;i<4;i++){let sel=base.cloneNode(true);sel.dataset.k=`${ds}|ferie|${i}`;sel.value='';sel.disabled=false;sel.onchange=async e=>{let x=await cloud(),schedule=x.schedule||{},k=e.target.dataset.k;if(e.target.value)schedule[k]=e.target.value;else delete schedule[k];await saveSchedule(schedule)};cell.appendChild(sel)}})}
const obs=new MutationObserver(enhanceLeaveCells);let table=$('schedule');if(table){obs.observe(table,{childList:true,subtree:true});enhanceLeaveCells()}

const svc={gessi:2,gessirep:1,reparto:2,amb:2,op1:2,op2:2,oppom:2,ferie:4};
const morning=['gessi','reparto','amb','op1','op2'],afternoon=['gessirep','oppom'];
const k=(ds,s,i)=>`${ds}|${s}|${i}`;
function vals(schedule,ds,list){let a=[];for(const s of list)for(let i=0;i<(svc[s]||1);i++){let v=schedule[k(ds,s,i)];if(v&&v!=='NESSUNO')a.push(v)}return a}
function weekKey(dt){let d=new Date(dt);d.setHours(12,0,0,0);let day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function onLeave(schedule,ds,n){return[0,1,2,3].some(i=>schedule[k(ds,'ferie',i)]===n)}
function eligible(n,s,w){if(n==='CIPRIAN')return s==='reparto';if(n==='LONDEI')return false;if(n==='PINI'){if(w===1)return false;if(!['op1','op2','oppom'].includes(s))return false;if(w===2&&s==='oppom')return false}if(n==='RIVA')return[1,2,3].includes(w)&&['gessi','amb'].includes(s);if(n==='FREGUIA')return[3,4,5].includes(w)&&s==='amb';if(s==='op2'&&![1,3,4,5].includes(w))return false;return true}
async function completeDoubleShifts(){let m=$('month')?.value;if(!m)return;let x=await cloud(),schedule=x.schedule||{},doctors=(x.doctors||[]).filter(d=>d.active),generated=new Set(x.generatedKeys||[]),names=doctors.map(d=>d.name),[y,mo]=m.split('-').map(Number),days=new Date(y,mo,0).getDate();
// PINI: sulle assegnazioni generate resta solo in sala operatoria, mai lunedi, max 3 turni per settimana.
let piniByWeek={};for(let d=1;d<=days;d++){let dt=new Date(y,mo-1,d),ds=`${m}-${String(d).padStart(2,'0')}`,wk=weekKey(dt);for(const [keyName,v] of Object.entries(schedule)){if(v!=='PINI'||!keyName.startsWith(ds+'|')||!generated.has(keyName))continue;let s=keyName.split('|')[1];if(dt.getDay()===1||!['op1','op2','oppom'].includes(s)||(dt.getDay()===2&&s==='oppom')){delete schedule[keyName];generated.delete(keyName);continue}(piniByWeek[wk]??=[]).push(keyName)}}for(const keys of Object.values(piniByWeek)){keys.sort((a,b)=>{let sa=a.split('|')[1],sb=b.split('|')[1];return(sa==='oppom')-(sb==='oppom')});for(const q of keys.slice(3)){delete schedule[q];generated.delete(q)}}
let doubles={};for(let d=1;d<=days;d++){let dt=new Date(y,mo-1,d),w=dt.getDay();if(w===0||w===6)continue;let ds=`${m}-${String(d).padStart(2,'0')}`,wk=weekKey(dt),am=new Set(vals(schedule,ds,morning)),pm=new Set(vals(schedule,ds,afternoon));for(const n of am)if(pm.has(n))doubles[`${wk}|${n}`]=(doubles[`${wk}|${n}`]||0)+1;
for(const s of [...morning,...afternoon])for(let i=0;i<svc[s];i++){if(i===1&&['gessi','amb'].includes(s))continue;let cell=k(ds,s,i);if(schedule[cell])continue;let phase=morning.includes(s)?'am':'pm',same=phase==='am'?am:pm,other=phase==='am'?pm:am;let cand=names.filter(n=>!same.has(n)&&!onLeave(schedule,ds,n)&&eligible(n,s,w));if(!cand.length)continue;cand.sort((a,b)=>{let ad=doubles[`${wk}|${a}`]||0,bd=doubles[`${wk}|${b}`]||0,ao=other.has(a)?1:0,bo=other.has(b)?1:0;let ap=a==='PINI'&&phase==='am'?-2:a==='PINI'?2:0,bp=b==='PINI'&&phase==='am'?-2:b==='PINI'?2:0;return(ao&&ad<1?0:ao?2:1)-(bo&&bd<1?0:bo?2:1)+ap-bp});let n=cand[0];schedule[cell]=n;generated.add(cell);same.add(n);if(other.has(n))doubles[`${wk}|${n}`]=(doubles[`${wk}|${n}`]||0)+1}}
}
await saveSchedule(schedule,[...generated]);location.reload()}
$('generate')?.addEventListener('click',()=>setTimeout(completeDoubleShifts,700));
