import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,doc,getDoc,setDoc,updateDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const cfg=await(await fetch('/__/firebase/init.json')).json(),fb=getApps()[0]||initializeApp(cfg),db=getFirestore(fb),root=doc(db,'gestionale','dati');let busy=false;
function monthLabel(m){const[y,mo]=m.split('-');return`${mo}/${y}`}
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,n=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*n+114)/31),da=(h+l-7*n+114)%31+1;return new Date(y,mo-1,da,12)}
function isHoliday(dt){const md=`${dt.getMonth()+1}-${dt.getDate()}`;if(new Set(['1-1','1-6','4-25','5-1','6-2','8-15','8-16','11-1','12-8','12-25','12-26']).has(md))return true;const p=easter(dt.getFullYear());p.setDate(p.getDate()+1);return p.toDateString()===dt.toDateString()}
function paintHolidays(){const m=document.getElementById('month')?.value;if(!m)return;document.querySelectorAll('#schedule tbody tr').forEach(r=>{const s=r.querySelector('select[data-k]');if(!s)return;const ds=s.dataset.k.split('|')[0],dt=new Date(ds+'T12:00:00');if(isHoliday(dt))r.classList.add('weekend')})}
async function saveVisibleState(){if(busy)return;const month=document.getElementById('month')?.value;if(!month)return;busy=true;const b=document.getElementById('saveStateBtn'),sync=document.getElementById('sync');try{if(b)b.disabled=true;if(sync)sync.textContent='Salvataggio stato manuale…';const snap=await getDoc(root),x=snap.exists()?snap.data():{},manual=new Set(x.manualKeys||[]),generated=new Set(x.generatedKeys||[]),contracts=new Set((x.doctors||[]).filter(d=>d.active&&d.cat==='Contratto').map(d=>d.name)),baseline={};document.querySelectorAll('#schedule select[data-k]').forEach(s=>{const k=s.dataset.k,v=s.value;if(!k?.startsWith(month+'-')||!v)return;const svc=k.split('|')[1],manualSvc=['guardia','giorno','esami','ferie'].includes(svc);if(manual.has(k)||manualSvc||!generated.has(k))baseline[k]=v});const savedStates={...(x.savedStates||{}),[month]:baseline},savedAbsenceStates={...(x.savedAbsenceStates||{}),[month]:structuredClone(x.absenceManagement||{})};for(const k of Object.keys(baseline)){manual.add(k);generated.delete(k)}await updateDoc(root,{savedStates,savedAbsenceStates,manualKeys:[...manual],generatedKeys:[...generated],updatedAt:new Date().toISOString()});if(sync){sync.textContent='● Stato manuale '+monthLabel(month)+' salvato';sync.className='status online'}}catch(err){if(sync)sync.textContent='Errore salvataggio stato';alert('Errore durante il salvataggio: '+err.message)}finally{busy=false;if(b)b.disabled=false}}
async function cleanNovemberBaseline(){
  const month=document.getElementById('month')?.value;
  if(month!=='2026-11')return alert('La pulizia mirata è disponibile solo per novembre 2026.');
  if(!confirm('Ripulire la baseline di novembre 2026 da RIVA e FREGUIA? La griglia corrente, i medici, le regole e gli altri mesi non verranno modificati.'))return;
  try{
    const snap=await getDoc(root),x=snap.exists()?snap.data():{},savedStates={...(x.savedStates||{})},b={...(savedStates['2026-11']||{})};
    const badKeys=Object.entries(b).filter(([k,v])=>k.startsWith('2026-11-')&&['RIVA','FREGUIA'].includes(v)).map(([k])=>k);
    for(const k of badKeys)delete b[k];
    savedStates['2026-11']=b;
    const manualKeys=(x.manualKeys||[]).filter(k=>!badKeys.includes(k));
    await updateDoc(root,{savedStates,manualKeys,updatedAt:new Date().toISOString()});
    alert('Baseline novembre 2026 ripulita. Rimossi '+badKeys.length+' riferimenti a RIVA/FREGUIA. La griglia corrente non è stata modificata.');
    await inspectBaseline();
  }catch(e){alert('Errore pulizia baseline: '+e.message)}
}
async function inspectBaseline(){const month=document.getElementById('month')?.value;if(!month)return;try{const snap=await getDoc(root),x=snap.exists()?snap.data():{},b=x.savedStates?.[month]||{},hits=Object.entries(b).filter(([k,v])=>k.startsWith(month+'-')&&['RIVA','FREGUIA'].includes(v));let msg='BASELINE '+month+'\nCelle salvate: '+Object.keys(b).filter(k=>k.startsWith(month+'-')).length+'\nRIVA: '+hits.filter(([,v])=>v==='RIVA').length+'\nFREGUIA: '+hits.filter(([,v])=>v==='FREGUIA').length;if(hits.length)msg+='\n\nOccorrenze:\n'+hits.map(([k,v])=>k+' = '+v).join('\n');else msg+='\n\nNessuna occorrenza RIVA/FREGUIA.';alert(msg)}catch(e){alert('Errore controllo baseline: '+e.message)}}
function install(){const gen=document.getElementById('generate');if(!gen)return;let b=document.getElementById('saveStateBtn');if(!b){b=document.createElement('button');b.id='saveStateBtn';b.type='button';b.textContent='SALVA STATO';b.className='adminOnly';gen.insertAdjacentElement('afterend',b)}let d=document.getElementById('inspectBaselineBtn');if(!d){d=document.createElement('button');d.id='inspectBaselineBtn';d.type='button';d.textContent='CONTROLLA BASELINE';d.className='adminOnly';b.insertAdjacentElement('afterend',d)}let c=document.getElementById('cleanNovemberBaselineBtn');if(!c){c=document.createElement('button');c.id='cleanNovemberBaselineBtn';c.type='button';c.textContent='RIPULISCI BASELINE NOV 2026';c.className='adminOnly danger';d.insertAdjacentElement('afterend',c)}if(d.dataset.bound!=='1'){d.dataset.bound='1';d.addEventListener('click',inspectBaseline)}if(c.dataset.bound!=='1'){c.dataset.bound='1';c.addEventListener('click',cleanNovemberBaseline)}if(b.dataset.saveStateBound!=='1'){b.dataset.saveStateBound='1';b.addEventListener('click',saveVisibleState)}paintHolidays()}
document.getElementById('month')?.addEventListener('change',e=>{const m=e.target.value;if(!m)return;localStorage.setItem('turniLastMonth',m);setTimeout(()=>location.reload(),80)},true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,500);setTimeout(install,1500);setTimeout(paintHolidays,2500);
