import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,doc,getDoc,setDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const $=id=>document.getElementById(id),cfg=await(await fetch('/__/firebase/init.json')).json(),fb=getApps()[0]||initializeApp(cfg),db=getFirestore(fb),root=doc(db,'gestionale','dati'),K=(d,s,i)=>`${d}|${s}|${i}`;
const DAY=['gessi','gessirep','reparto','amb','esami','op1','op2','oppom'],PM=['gessirep','oppom'],REQ=['gessi','gessirep','reparto','amb','esami','op1','op2','oppom'],AUTO=['disp1','disp2',...REQ];
async function cloud(){let s=await getDoc(root);return s.exists()?s.data():{}}
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=(h+l-7*m+114)%31+1;return new Date(y,mo-1,da,12)}
function holiday(dt){let md=`${dt.getMonth()+1}-${dt.getDate()}`,fixed=new Set(['1-1','1-6','4-25','5-1','6-2','8-15','8-16','11-1','12-8','12-25','12-26']);if(fixed.has(md))return true;let p=easter(dt.getFullYear());p.setDate(p.getDate()+1);return p.toDateString()===dt.toDateString()}
function workTarget(m){let[y,mo]=m.split('-').map(Number),n=0,days=new Date(y,mo,0).getDate();for(let d=1;d<=days;d++){let x=new Date(y,mo-1,d,12);if(x.getDay()!==0&&!holiday(x))n++}return n}
function target(n,m){let[y,mo]=m.split('-').map(Number),days=new Date(y,mo,0).getDate(),wds=n==='ARMATO'||n==='CIPRIAN'?[1,2,3,4,5]:n==='RIVA'?[1,2,3]:n==='FREGUIA'?[3,4,5]:null;if(wds){let q=0;for(let d=1;d<=days;d++){let x=new Date(y,mo-1,d,12);if(wds.includes(x.getDay())&&!holiday(x))q++}return q}if(n==='PINI')return Math.round(days/7*3);return workTarget(m)}
function hrs(s,dt){if(s==='guardia')return 12;if(s==='ferie'||s==='giorno')return 6;if(['disp1','disp2'].includes(s))return[0,6].includes(dt.getDay())?6:0;return 6}
function leave(sch,ds,n){return[0,1,2,3].some(i=>sch[K(ds,'ferie',i)]===n)}
function weekStart(ds){let d=new Date(ds+'T12:00:00'),w=d.getDay()||7;d.setDate(d.getDate()-w+1);return d.toISOString().slice(0,10)}
function weekHours(sch,n,ds){let wk=weekStart(ds),q=0;for(const[k,v]of Object.entries(sch)){if(v!==n)continue;let[a,s]=k.split('|');if(weekStart(a)!==wk)continue;q+=hrs(s,new Date(a+'T12:00:00'))}return q}
function monthEq(sch,n,m){let q=0;for(const[k,v]of Object.entries(sch)){if(v!==n||!k.startsWith(m+'-'))continue;let[ds,s]=k.split('|');q+=hrs(s,new Date(ds+'T12:00:00'))/6}return q}
function dayHours(sch,n,ds){let q=0;for(const[k,v]of Object.entries(sch)){if(v!==n||!k.startsWith(ds+'|'))continue;let s=k.split('|')[1];if(DAY.includes(s))q+=6}return q}
function doubles(sch,n,ds){let wk=weekStart(ds),days={};for(const[k,v]of Object.entries(sch)){if(v!==n)continue;let[a,s]=k.split('|');if(weekStart(a)!==wk||!DAY.includes(s))continue;days[a]=(days[a]||0)+6}return Object.values(days).filter(x=>x>=12).length}
function guard(sch,ds,n){return sch[K(ds,'guardia',0)]===n}
function prevDay(ds){let d=new Date(ds+'T12:00:00');d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)}
function nextMorningPenalty(sch,ds,n){return sch[K(prevDay(ds),'disp1',0)]===n?1:0}
function freePm(n,w){return(n==='VIALE'&&w===3)||(n==='CALZAVARA'&&w===2)||(n==='COMELATO'&&[1,4].includes(w))||(n==='FRANCO'&&w===3)}
function eligible(d,s,dt){let n=d.name,w=dt.getDay();if(['PINI','LONDEI'].includes(n))return false;if(n==='RIVA')return[1,2,3].includes(w)&&['gessi','amb'].includes(s);if(n==='FREGUIA')return[3,4,5].includes(w)&&s==='amb';if(n==='ARMATO')return w>=1&&w<=5&&['op1','op2'].includes(s);if(n==='CIPRIAN')return w>=1&&w<=5&&s==='reparto';if(PM.includes(s)&&freePm(n,w))return false;return d.cat==='Strutturato'}
function can(sch,d,s,ds,m,allowExtra=false){let dt=new Date(ds+'T12:00:00'),n=d.name;if(leave(sch,ds,n)||guard(sch,ds,n)||guard(sch,prevDay(ds),n)||!eligible(d,s,dt))return false;let h=hrs(s,dt),lim=Number(d.hours)||36;if(weekHours(sch,n,ds)+h>lim)return false;if(DAY.includes(s)){let dh=dayHours(sch,n,ds);if(dh>=12)return false;if(dh>=6&&doubles(sch,n,ds)>=1)return false}let t=target(n,m);if(!allowExtra&&monthEq(sch,n,m)+h/6>t)return false;return true}
function assign(sch,gen,extra,k,n,isExtra=false){sch[k]=n;gen.add(k);isExtra?extra.add(k):extra.delete(k)}
function clearGeneratedMonth(sch,gen,extra,m){for(const k of [...gen])if(k.startsWith(m+'-')){delete sch[k];gen.delete(k);extra.delete(k)}}
function slotsFor(s){return['gessi','amb'].includes(s)?[0]:[0,1]}
function candidates(doctors,sch,s,ds,m,allowExtra=false){return doctors.filter(d=>can(sch,d,s,ds,m,allowExtra)).sort((a,b)=>nextMorningPenalty(sch,ds,a.name)-nextMorningPenalty(sch,ds,b.name)||monthEq(sch,a.name,m)-monthEq(sch,b.name,m)||weekHours(sch,a.name,ds)-weekHours(sch,b.name,ds))}
async function generateV2(){let m=$('month')?.value;if(!m)return;let x=await cloud(),doctors=(x.doctors||[]).filter(d=>d.active),sch={...(x.schedule||{})},gen=new Set(x.generatedKeys||[]),extra=new Set(x.extraKeys||[]),[y,mo]=m.split('-').map(Number),days=new Date(y,mo,0).getDate();clearGeneratedMonth(sch,gen,extra,m);
// Ferie prevalgono sempre sulle assegnazioni automatiche pregresse.
for(const[k,n]of Object.entries(sch)){let[ds,s]=k.split('|');if(!ds.startsWith(m+'-')||s==='ferie'||!leave(sch,ds,n))continue;if(gen.has(k)){delete sch[k];gen.delete(k);extra.delete(k)}}
// 1) Contratti: RIVA e FREGUIA prima di chiunque altro. LONDEI resta manuale.
for(const spec of [{n:'RIVA',wd:[1,2,3],svc:['gessi','amb']},{n:'FREGUIA',wd:[3,4,5],svc:['amb']}]){let d=doctors.find(z=>z.name===spec.n);if(!d)continue;for(let day=1;day<=days&&monthEq(sch,d.name,m)<target(d.name,m);day++){let dt=new Date(y,mo-1,day,12),ds=`${m}-${String(day).padStart(2,'0')}`;if(holiday(dt)||!spec.wd.includes(dt.getDay()))continue;for(const s of spec.svc){let k=K(ds,s,0);if((!sch[k]||sch[k]==='NESSUNO')&&can(sch,d,s,ds,m)){assign(sch,gen,extra,k,d.name);break}}}}
// 2) CIPRIAN e ARMATO nelle rispettive attività dedicate.
for(let day=1;day<=days;day++){let dt=new Date(y,mo-1,day,12),w=dt.getDay(),ds=`${m}-${String(day).padStart(2,'0')}`;if(w===0||w===6||holiday(dt))continue;for(const spec of [{n:'CIPRIAN',svc:['reparto']},{n:'ARMATO',svc:['op1','op2']}]){let d=doctors.find(z=>z.name===spec.n);if(!d)continue;for(const s of spec.svc){let k=K(ds,s,0);if((!sch[k]||sch[k]==='NESSUNO')&&can(sch,d,s,ds,m)){assign(sch,gen,extra,k,d.name);break}}}}
// 3) Strutturati: prima entro target, poi extra solo se serve a coprire un servizio obbligatorio.
for(let day=1;day<=days;day++){let dt=new Date(y,mo-1,day,12),w=dt.getDay(),ds=`${m}-${String(day).padStart(2,'0')}`;if(w===0||w===6||holiday(dt))continue;for(const s of AUTO){let slots=['disp1','disp2'].includes(s)?[0]:slotsFor(s);for(const i of slots){let k=K(ds,s,i);if(sch[k]&&sch[k]!=='NESSUNO')continue;let c=candidates(doctors,sch,s,ds,m,false);if(c[0])assign(sch,gen,extra,k,c[0].name);else if(REQ.includes(s)){let e=candidates(doctors,sch,s,ds,m,true).filter(d=>d.cat==='Strutturato');if(e[0])assign(sch,gen,extra,k,e[0].name,true)}}}}
await setDoc(root,{schedule:sch,generatedKeys:[...gen],extraKeys:[...extra],updatedAt:new Date().toISOString()},{merge:true});location.reload()}
function install(){let b=$('generate');if(!b||b.dataset.v2)return;b.dataset.v2='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();generateV2().catch(err=>alert('Errore generazione: '+err.message))},true)}
// Evidenzia gli extra nella griglia mensile usando extraKeys salvati.
async function paintExtras(){let x=await cloud(),ex=new Set(x.extraKeys||[]);document.querySelectorAll('#schedule select[data-k]').forEach(s=>s.classList.toggle('extraShift',ex.has(s.dataset.k)))}
function start(){install();paintExtras();new MutationObserver(()=>{install();paintExtras()}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();