import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,doc,getDoc,setDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const $=id=>document.getElementById(id),cfg=await(await fetch('/__/firebase/init.json')).json(),fb=getApps()[0]||initializeApp(cfg),db=getFirestore(fb),root=doc(db,'gestionale','dati'),K=(d,s,i)=>`${d}|${s}|${i}`;
const AM=['gessi','reparto','amb','esami','op1','op2'],PM=['gessirep','oppom'],DAY=[...AM,...PM],REQ=['op1','op2','oppom','gessi','gessirep','reparto','amb'],OR=['op1','op2','oppom'],OPFIRST=['op1','op2','oppom'],REST=['gessi','gessirep','reparto','amb'];
const manualOnly=d=>d?.cat==='Contratto'||['ARMATO','PINI'].includes(d?.name);
async function cloud(){let s=await getDoc(root);return s.exists()?s.data():{}}
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=(h+l-7*m+114)%31+1;return new Date(y,mo-1,da,12)}
function holiday(dt){let md=`${dt.getMonth()+1}-${dt.getDate()}`,f=new Set(['1-1','1-6','4-25','5-1','6-2','8-15','8-16','11-1','12-8','12-25','12-26']);if(f.has(md))return true;let p=easter(dt.getFullYear());p.setDate(p.getDate()+1);return p.toDateString()===dt.toDateString()}
function workTarget(m){let[y,mo]=m.split('-').map(Number),n=0,z=new Date(y,mo,0).getDate();for(let d=1;d<=z;d++){let x=new Date(y,mo-1,d,12);if(x.getDay()!==0&&!holiday(x))n++}return n}
function target(n,m){if(n==='CIPRIAN'){let[y,mo]=m.split('-').map(Number),z=new Date(y,mo,0).getDate(),q=0;for(let d=1;d<=z;d++){let x=new Date(y,mo-1,d,12);if(x.getDay()>=1&&x.getDay()<=5&&!holiday(x))q++}return q}return workTarget(m)}
function hrs(s,dt){if(s==='guardia')return 12;if(s==='ferie'||s==='giorno')return 6;if(['disp1','disp2'].includes(s))return[0,6].includes(dt.getDay())?6:0;return 6}
function leave(a,ds,n){return[0,1,2,3].some(i=>a[K(ds,'ferie',i)]===n)}
function wk(ds){let d=new Date(ds+'T12:00:00'),w=d.getDay()||7;d.setDate(d.getDate()-w+1);return d.toISOString().slice(0,10)}
function weekHours(a,n,ds){let q=0,W=wk(ds);for(const[k,v]of Object.entries(a))if(v===n){let[x,s]=k.split('|');if(wk(x)===W)q+=hrs(s,new Date(x+'T12:00:00'))}return q}
function monthEq(a,n,m){let q=0;for(const[k,v]of Object.entries(a))if(v===n&&k.startsWith(m+'-')){let[ds,s]=k.split('|');q+=hrs(s,new Date(ds+'T12:00:00'))/6}return q}
function orCount(a,n,m){let q=0;for(const[k,v]of Object.entries(a))if(v===n&&k.startsWith(m+'-')&&OR.includes(k.split('|')[1]))q++;return q}
function opMatCount(a,n,m){let q=0;for(const[k,v]of Object.entries(a))if(v===n&&k.startsWith(m+'-')&&['op1','op2'].includes(k.split('|')[1]))q++;return q}
function opPomCount(a,n,m){let q=0;for(const[k,v]of Object.entries(a))if(v===n&&k.startsWith(m+'-')&&k.split('|')[1]==='oppom')q++;return q}
function shiftDay(ds,delta){let d=new Date(ds+'T12:00:00');d.setDate(d.getDate()+delta);return d.toISOString().slice(0,10)}
function hasSameShift(a,n,s,ds){return Object.entries(a).some(([k,v])=>v===n&&k.startsWith(ds+'|'+s+'|'))}
function createsThreeConsecutive(a,n,s,ds){if(!REQ.includes(s))return false;let h=o=>hasSameShift(a,n,s,shiftDay(ds,o));return(h(-2)&&h(-1))||(h(-1)&&h(1))||(h(1)&&h(2))}
function hasBand(a,n,ds,band){let set=band==='am'?AM:PM;return Object.entries(a).some(([k,v])=>v===n&&k.startsWith(ds+'|')&&set.includes(k.split('|')[1]))}
function doubles(a,n,ds){let W=wk(ds),d={};for(const[k,v]of Object.entries(a))if(v===n){let[x,s]=k.split('|');if(wk(x)===W&&DAY.includes(s)){d[x]??={am:false,pm:false};if(AM.includes(s))d[x].am=true;if(PM.includes(s))d[x].pm=true}}return Object.values(d).filter(x=>x.am&&x.pm).length}
function guard(a,ds,n){return a[K(ds,'guardia',0)]===n}function prev(ds){return shiftDay(ds,-1)}
function freePm(n,w){return(n==='VIALE'&&w===3)||(n==='CALZAVARA'&&w===2)||(n==='COMELATO'&&[1,4].includes(w))||(n==='FRANCO'&&w===3)}
function eligible(d,s,dt,force=false){let n=d.name,w=dt.getDay();if(manualOnly(d))return false;if(n==='CIPRIAN')return w>=1&&w<=5&&s==='reparto';if(!force&&PM.includes(s)&&freePm(n,w))return false;return d.cat==='Strutturato'}
function can(a,d,s,ds,m,extra=false,force=false){let dt=new Date(ds+'T12:00:00'),n=d.name;if(leave(a,ds,n)||guard(a,ds,n)||guard(a,prev(ds),n)||!eligible(d,s,dt,force)||(n!=='CIPRIAN'&&createsThreeConsecutive(a,n,s,ds)))return false;if(!extra&&weekHours(a,n,ds)+hrs(s,dt)>(Number(d.hours)||36))return false;if(AM.includes(s)){if(hasBand(a,n,ds,'am'))return false;if(hasBand(a,n,ds,'pm')&&doubles(a,n,ds)>=1)return false}if(PM.includes(s)){if(hasBand(a,n,ds,'pm'))return false;if(hasBand(a,n,ds,'am')&&doubles(a,n,ds)>=1)return false}return extra||n==='CIPRIAN'||monthEq(a,n,m)+hrs(s,dt)/6<=target(n,m)}
function assign(a,g,e,k,n,x=false){a[k]=n;g.add(k);x?e.add(k):e.delete(k)}
function clear(a,g,e,m,doctors,protectedKeys){let contracts=new Set(doctors.filter(manualOnly).map(d=>d.name));for(const k of [...g])if(k.startsWith(m+'-')){if(protectedKeys.has(k)||contracts.has(a[k])){g.delete(k);e.delete(k);continue}delete a[k];g.delete(k);e.delete(k)}}
function slots(s){return['gessi','amb','gessirep'].includes(s)?[0]:[0,1]}
function dispCount(a,n,m,s){let q=0;for(const[k,v]of Object.entries(a))if(v===n&&k.startsWith(m+'-')&&k.split('|')[1]===s)q++;return q}
function dispOK(a,d,ds,s){let n=d.name;if(d.cat!=='Strutturato'||manualOnly(d)||leave(a,ds,n)||guard(a,ds,n)||guard(a,prev(ds),n))return false;let other=s==='disp1'?'disp2':'disp1';return a[K(ds,other,0)]!==n}
function assignDisp(a,g,e,doctors,ds,m,s,protectedKeys){let k=K(ds,s,0);if(protectedKeys.has(k)||a[k]&&a[k]!=='NESSUNO')return;let c=doctors.filter(d=>dispOK(a,d,ds,s)).sort((x,y)=>dispCount(a,x.name,m,s)-dispCount(a,y.name,m,s)||monthEq(a,x.name,m)-monthEq(a,y.name,m));if(c[0])assign(a,g,e,k,c[0].name)}
function cand(doctors,a,s,ds,m,x=false,force=false){return doctors.filter(d=>can(a,d,s,ds,m,x,force)).sort((p,q)=>(['op1','op2'].includes(s)?opMatCount(a,p.name,m)-opMatCount(a,q.name,m):0)||(s==='oppom'?opPomCount(a,p.name,m)-opPomCount(a,q.name,m):0)||(OR.includes(s)?orCount(a,p.name,m)-orCount(a,q.name,m):0)||monthEq(a,p.name,m)-monthEq(a,q.name,m)||weekHours(a,p.name,ds)-weekHours(a,q.name,ds))}
function monthDays(m,days,y,mo){let out=[];for(let day=1;day<=days;day++){let dt=new Date(y,mo-1,day,12),w=dt.getDay();if(w===0||w===6||holiday(dt))continue;out.push({dt,ds:`${m}-${String(day).padStart(2,'0')}`})}return out}
function assignServiceMonth(a,g,e,doctors,m,dates,s,protectedKeys){for(const{ds}of dates)for(const i of slots(s)){let k=K(ds,s,i);if(protectedKeys.has(k)||a[k]&&a[k]!=='NESSUNO')continue;let c=cand(doctors,a,s,ds,m,false,false);if(c[0])assign(a,g,e,k,c[0].name)}}
function fillHoles(a,g,e,doctors,m,days,y,mo,protectedKeys){for(let pass=0;pass<6;pass++){let changed=false;for(let day=1;day<=days;day++){let dt=new Date(y,mo-1,day,12),w=dt.getDay(),ds=`${m}-${String(day).padStart(2,'0')}`;if(w===0||w===6||holiday(dt))continue;for(const s of REQ)for(const i of slots(s)){let k=K(ds,s,i);if(protectedKeys.has(k)||a[k]&&a[k]!=='NESSUNO')continue;let c=cand(doctors,a,s,ds,m,true,false).filter(d=>d.cat==='Strutturato'&&!manualOnly(d));if(!c[0])c=cand(doctors,a,s,ds,m,true,true).filter(d=>d.cat==='Strutturato'&&!manualOnly(d));if(c[0]){assign(a,g,e,k,c[0].name,true);changed=true}}}if(!changed)break}}
function assignCiprian(a,g,e,m,days,y,mo,protectedKeys){for(let day=1;day<=days;day++){let dt=new Date(y,mo-1,day,12),w=dt.getDay(),ds=`${m}-${String(day).padStart(2,'0')}`;if(w<1||w>5||holiday(dt)||leave(a,ds,'CIPRIAN'))continue;let k0=K(ds,'reparto',0),k1=K(ds,'reparto',1);if(a[k0]==='CIPRIAN'||a[k1]==='CIPRIAN')continue;let opts=[k0,k1].filter(k=>!protectedKeys.has(k)&&(!a[k]||a[k]==='NESSUNO'));if(opts[0])assign(a,g,e,opts[0],'CIPRIAN')}}
function normalizeExtras(a,g,e,doctors,m){for(const k of [...e])if(k.startsWith(m+'-'))e.delete(k);for(const d of doctors){if(manualOnly(d))continue;let over=Math.max(0,monthEq(a,d.name,m)-target(d.name,m));if(!over)continue;let keys=[...g].filter(k=>k.startsWith(m+'-')&&a[k]===d.name&&REQ.includes(k.split('|')[1])).sort().reverse();for(const k of keys){if(over<=0)break;e.add(k);over-=1}}}
function unresolved(a,m,days,y,mo,protectedKeys){let u=[];for(let day=1;day<=days;day++){let dt=new Date(y,mo-1,day,12),w=dt.getDay(),ds=`${m}-${String(day).padStart(2,'0')}`;if(w===0||w===6||holiday(dt))continue;for(const s of REQ)for(const i of slots(s)){let k=K(ds,s,i);if(protectedKeys.has(k))continue;if(!a[k]||a[k]==='NESSUNO')u.push(k)}}return u}
async function generateV2(){let m=$('month')?.value;if(!m)return;localStorage.setItem('turniLastMonth',m);await new Promise(r=>setTimeout(r,550));let x=await cloud(),doctors=(x.doctors||[]).filter(d=>d.active),a={...(x.schedule||{})},g=new Set(x.generatedKeys||[]),e=new Set(x.extraKeys||[]),baseline=x.savedStates?.[m]||{},protectedKeys=new Set(Object.keys(baseline)),[y,mo]=m.split('-').map(Number),days=new Date(y,mo,0).getDate(),dates=monthDays(m,days,y,mo);clear(a,g,e,m,doctors,protectedKeys);for(const[k,v]of Object.entries(baseline))if(k.startsWith(m+'-'))a[k]=v;for(const{ds}of dates){let k=K(ds,'esami',0);if(!protectedKeys.has(k)&&!a[k])a[k]='NESSUNO'}for(const s of OPFIRST)assignServiceMonth(a,g,e,doctors,m,dates,s,protectedKeys);assignCiprian(a,g,e,m,days,y,mo,protectedKeys);for(const s of REST)assignServiceMonth(a,g,e,doctors,m,dates,s,protectedKeys);for(const{ds}of dates){assignDisp(a,g,e,doctors,ds,m,'disp1',protectedKeys);assignDisp(a,g,e,doctors,ds,m,'disp2',protectedKeys)}fillHoles(a,g,e,doctors,m,days,y,mo,protectedKeys);assignCiprian(a,g,e,m,days,y,mo,protectedKeys);normalizeExtras(a,g,e,doctors,m);let u=unresolved(a,m,days,y,mo,protectedKeys),allU=new Set(x.unresolvedKeys||[]);for(const k of [...allU])if(k.startsWith(m+'-'))allU.delete(k);u.forEach(k=>allU.add(k));await setDoc(root,{schedule:a,generatedKeys:[...g],extraKeys:[...e],unresolvedKeys:[...allU],updatedAt:new Date().toISOString()},{merge:true});location.reload()}
function ensureStyle(){if(document.getElementById('unresolvedStyle'))return;let s=document.createElement('style');s.id='unresolvedStyle';s.textContent='select.unresolvedShift{background:#fff3cd!important;border:3px solid #f59e0b!important;box-shadow:0 0 0 1px #b45309!important}';document.head.appendChild(s)}
async function paintUnresolved(){ensureStyle();let x=await cloud(),u=new Set(x.unresolvedKeys||[]),m=$('month')?.value||'';document.querySelectorAll('#schedule select[data-k]').forEach(s=>s.classList.toggle('unresolvedShift',!!m&&u.has(s.dataset.k)))}
function restoreMonth(){let el=$('month'),m=localStorage.getItem('turniLastMonth');if(el&&m&&/^\d{4}-\d{2}$/.test(m))el.value=m}
async function saveState(){let m=$('month')?.value;if(!m)return;let x=await cloud(),a={...(x.schedule||{})},g=new Set(x.generatedKeys||[]),manual=new Set(x.manualKeys||[]),baseline={};document.querySelectorAll('#schedule select[data-k]').forEach(s=>{let k=s.dataset.k,v=s.value;if(!k?.startsWith(m+'-')||!v)return;let svc=k.split('|')[1],d=(x.doctors||[]).find(z=>z.name===v);if(manual.has(k)||['guardia','giorno','esami','ferie'].includes(svc)||manualOnly(d)||(!g.has(k)&&v==='NESSUNO'))baseline[k]=v});let savedStates={...(x.savedStates||{}),[m]:baseline};await setDoc(root,{savedStates,updatedAt:new Date().toISOString()},{merge:true});$('sync').textContent='● Stato manuale salvato';$('sync').className='status online'}
async function clearDraft(){let m=$('month')?.value;if(!m)return;let x=await cloud(),baseline=x.savedStates?.[m];if(!confirm(baseline?`Cancellare la bozza automatica di ${m}? Verrà ripristinato esattamente l'ultimo SALVA STATO.`:`Cancellare la bozza automatica di ${m}? Verranno rimossi solo i turni generati automaticamente.`))return;let a={...(x.schedule||{})},g=new Set(x.generatedKeys||[]),e=new Set(x.extraKeys||[]),u=new Set(x.unresolvedKeys||[]),manual=new Set(x.manualKeys||[]);if(baseline){for(const k of Object.keys(a))if(k.startsWith(m+'-'))delete a[k];for(const[k,v]of Object.entries(baseline))if(k.startsWith(m+'-'))a[k]=v}else for(const k of [...g])if(k.startsWith(m+'-')&&!manual.has(k))delete a[k];for(const set of[g,e,u])for(const k of [...set])if(k.startsWith(m+'-'))set.delete(k);await setDoc(root,{schedule:a,generatedKeys:[...g],extraKeys:[...e],unresolvedKeys:[...u],updatedAt:new Date().toISOString()},{merge:true});location.reload()}
async function persistManual(s){let k=s.dataset.k;if(!k)return;let x=await cloud(),a={...(x.schedule||{})},manual=new Set(x.manualKeys||[]),g=new Set(x.generatedKeys||[]),e=new Set(x.extraKeys||[]);if(s.value){a[k]=s.value;manual.add(k)}else{delete a[k];manual.delete(k)}g.delete(k);e.delete(k);await setDoc(root,{schedule:a,manualKeys:[...manual],generatedKeys:[...g],extraKeys:[...e],updatedAt:new Date().toISOString()},{merge:true})}
function install(){if(document.documentElement.dataset.schedulerV12)return;document.documentElement.dataset.schedulerV12='1';document.addEventListener('click',q=>{let b=q.target.closest?.('#generate,#saveStateBtn,#clearDraft');if(!b)return;q.preventDefault();q.stopImmediatePropagation();if(b.id==='generate')generateV2().catch(err=>alert('Errore generazione: '+err.message));else if(b.id==='saveStateBtn')saveState().catch(err=>alert('Errore salvataggio stato: '+err.message));else clearDraft().catch(err=>alert('Errore cancellazione: '+err.message))},true);document.addEventListener('change',e=>{let s=e.target;if(!(s instanceof HTMLSelectElement)||!s.dataset.k)return;if(s.matches('#schedule select.unresolvedShift'))s.classList.remove('unresolvedShift');persistManual(s).catch(()=>{})},true)}
function start(){restoreMonth();install();paintUnresolved();new MutationObserver(()=>{install();paintUnresolved()}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();